// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9-_OU_QzmQNM0orp2XBfEmDY4SRtyqc',
    appId: '1:894766501636:web:31aadbd04d08c9f2164a51',
    messagingSenderId: '894766501636',
    projectId: 'turath-b31e8',
    authDomain: 'turath-b31e8.firebaseapp.com',
    storageBucket: 'turath-b31e8.appspot.com',
    measurementId: 'G-B0LY9FXMK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6O5BwTXlnGwpL3Sp7co5VIgSKnu5Cn4',
    appId: '1:894766501636:android:d66954c0019880d6164a51',
    messagingSenderId: '894766501636',
    projectId: 'turath-b31e8',
    storageBucket: 'turath-b31e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOc2oTbYmpdoQtP5i9Hln9JhDwohzma8Q',
    appId: '1:894766501636:ios:5a4d2155448d78fb164a51',
    messagingSenderId: '894766501636',
    projectId: 'turath-b31e8',
    storageBucket: 'turath-b31e8.appspot.com',
    iosBundleId: 'com.depi.turath',
  );
}
