name: turath
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
    

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Fustat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fustat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fustat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fustat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fustat-Light.ttf
          weight: 300
        - asset: assets/fonts/Fustat-ExtraLight.ttf
          weight: 200

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_assets.dart
  field_prefix: null



